<<<<<<<< HEAD:.github/workflows/app-build.yml
name: AppBuild
========
name: @awesome-ng/let build
>>>>>>>> 2925707 (workflow build update):.github/workflows/ang-let-build.yml
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup
        run: npm ci

      - name: Test
        run: npm run test:ci ang-let

      - name: Build
        run: npm run build:prod --project ang-let