name: '@awesome-ng/let'
on:
  push:
    paths:
      - 'projects/ang-let/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup
        run: npm ci

      - name: Test
        run: npm run test:ci ang-let

      - name: Build
        run: npm run build:prod --project ang-let
